server:
  port: 8002
spring:
  application:
    name: comsumer-user


eureka:
  instance:
    prefer-ip-address: true #注册服务时用ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/